first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Ts: 0.001 #sample time
    k: 100 #400
    b: 4
    bdrain: 40.0 #drainage damping
    alpha: 1 #low pass filter constant
    accuracy_thr: 0.002 #[m]
    k_modulation_factor: 3000000 #8.0
    kmax: 400 #maximumum allowable translational stiffness in case of modulating stiffness
    b_modulation_factor: 0.001
    bmax: 20
    eps_low: 0.3 #0.3 #Energy minimum in tanks [J]
    eps_high: 0.9 #0.9 #Energy maximum in the tanks [J] 
    epsP: 50.1 #Power margin for collision detection [W]
    epsE: 0.6 #Energy margin in the tanks or this value is a % of the total expected energy spend
    Ek_drained: 0.001 #maximum kinetic energy of the robot when it is assumed to be drained
    z_compression: 0.1536 
    use_TB: true  #wether or not we want to include feed-forward 
    use_modulated_TF: true #bool for using an increasing TF stiffness
    use_dynamic_injection: true #bool for dynamically injection energy in the energy tanks
    use_prev_power_data: true #wether or not to use data from previous trajectory
    torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_TB_torques.txt'
    Hv0_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_Hn0.txt'
    qi_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_q0.txt'
    t_flag_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_t_flag.txt'
    qdot_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_qdot.txt'
    tauc_gravity_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_tauc_gravity.txt'
    q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V9_var_env_q.txt'
    prev_torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_7_tau_measured.txt'
    prev_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_7_dq.txt'
    prev_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_7_q.txt'
    kp: 1 #This value is modified, so not actually a "kp"
    kd: 5
    dataPrint: true
    dataAnalysis_tau_TB_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_tau_TB.txt'
    dataAnalysis_tau_TF_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_tau_TF.txt'
    dataAnalysis_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_dq.txt'
    dataAnalysis_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_q.txt'
    dataAnalysis_tau_measured_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_tau_measured.txt'
    dataAnalysis_tau_desired_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_tau_desired.txt'
    dataAnalysis_xyz_ref_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_xyz_ref.txt'
    dataAnalysis_accuracy_thr_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V9_var_env_15_accuracy_thr.txt'