first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k: 15
    b: 3
    xd: 0.3
    yd: 0.2
    zd: 0.25
    theta: 0
    psi: 0
    phi: 3.1415
    
  