first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    kt: 100
    ko: 100
    b: 2
    bdrain: 2.0 #drainage damping
    xd: 0.5
    yd: 0.0
    zd: 0.1
    theta: 0
    psi: 0
    phi: 3.1415
    accuracy_thr: 0.01 #[m]
    modulation_factor: 10.0
    epsP: 50.1 #Power margin for collision detection [W]
    epsE: 50.025 #Energy margin in the tanks, this value is a % of the total expected energy spend
    TaskBased: false #wether or not we want to include feed-forward 
    use_optimisation: true #IF SET TO FALSE MAKE SURE THE IMPEDANCE PARAMS ARE LOWER!!!!
    use_modulated_TF: true #bool for using an increasing TF stiffness
    use_cyclic: false #bool for using completing the trajectory repetivily 
    use_dynamic_injection: true #bool for dynamically injection energy in the energy tanks
    torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V10_var_TB_torques.txt'
    Hv0_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V10_var_Hn0.txt'
    qi_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V10_var_q0.txt'
    t_flag_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V10_var_t_flag.txt'
    kp: 1 #This value is modified, so not actually a "kp"
    kd: 5
    cycle_wait_period: 3000 #wait period between cycles in milliseconds
    dataPrint: false
    dataAnalysis_tau_TB_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_tau_TB.txt'
    dataAnalysis_tau_TF_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_tau_TF.txt'
    dataAnalysis_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_dq.txt'
    dataAnalysis_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_q.txt'
    dataAnalysis_tau_measured_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_opt_tau_measured.txt'
    dataAnalysis_tau_desired_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V7_var_opt_tau_desired.txt'