first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    kt: 400
    ko: 400
    b: 10
    xd: 0.5
    yd: 0.0
    zd: 0.1
    theta: 0
    psi: 0
    phi: 3.1415
    accuracy_thr: 0.03 #[m]
    modulation_factor: 0.5
    TaskBased: false
    use_optimisation: true #IF SET TO FALSE MAKE SURE THE IMPEDANCE PARAMS ARE LOWER!!!!
    use_modulated_TF: true 
    torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V2_var_TB_torques.txt'
    Hv0_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V2_var_Hn0.txt'
    qi_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V2_var_q0.txt'
    t_flag_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/V2_var_t_flag.txt'
    kp: 1
    kd: 5
    dataPrint: false
    dataAnalysis_tau_TB_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V2_var_TF_tau_TB.txt'
    dataAnalysis_tau_TF_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V2_var_TF_tau_TF.txt'
    dataAnalysis_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V2_var_TF_dq.txt'
    dataAnalysis_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V2_var_TF_q.txt'
    dataAnalysis_tau_measured_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V2_var_TF_tau_measured.txt'