first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    kt: 400
    ko: 400
    b: 50
    xd: 0.4
    yd: 0
    zd: 0.5
    theta: 0
    psi: 0
    phi: 3.1415
    TaskBased: false
    use_optimisation: true #IF SET TO FALSE MAKE SURE THE IMPEDANCE PARAMS ARE LOWER!!!!
    torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/TB_torques_V7.txt'
    Hv0_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Hn0_V7.txt'
    qi_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/q0_V7.txt'
    kp: 100
    kd: 10
    dataPrint: true
    dataAnalysis_tau_TB_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/Vtest_tau_TB.txt'
    dataAnalysis_tau_TF_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/Vtest_tau_TF.txt'
    dataAnalysis_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/Vtest_dq.txt'
    dataAnalysis_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/Vtest_q.txt'