first_controller:
    type: new_controllers/FirstController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Ts: 0.001 #sample time
    kt: 400 #400
    ko: 200 #400
    b: 4
    bdrain: 40.0 #drainage damping
    alpha: 1 #low pass filter constant
    accuracy_thr: 0.002 #[m]
    kt_modulation_factor: 3000000 #8.0
    ko_modulation_factor: 3000000
    ktmax: 5000 #maximumum allowable translational stiffness in case of modulating stiffness
    komax: 300 #maximumum allowable rotational stiffness in case of modulating stiffness
    b_modulation_factor: 0.001
    bmax: 20
    eps: 0.01 #Energy minimum in tanks [J]
    epsP: 50.1 #Power margin for collision detection [W]
    epsE: 0.1 #Energy margin in the tanks, this value is a % of the total expected energy spend
    Ek_drained: 0.001 #maximum kinetic energy of the robot when it is assumed to be drained
    use_TB: false #wether or not we want to include feed-forward 
    use_modulated_TF: true #bool for using an increasing TF stiffness
    use_dynamic_injection: true #bool for dynamically injection energy in the energy tanks
    torque_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_TB_torques.txt'
    Hv0_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_Hn0.txt'
    qi_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_q0.txt'
    t_flag_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_t_flag.txt'
    qdot_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_qdot.txt'
    tauc_gravity_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/OptimisationData/Venv_height_test_tauc_gravity.txt'
    kp: 1 #This value is modified, so not actually a "kp"
    kd: 5
    dataPrint: false
    dataAnalysis_tau_TB_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_tau_TB.txt'
    dataAnalysis_tau_TF_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_tau_TF.txt'
    dataAnalysis_dq_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_dq.txt'
    dataAnalysis_q_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_q.txt'
    dataAnalysis_tau_measured_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_tau_measured.txt'
    dataAnalysis_tau_desired_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_tau_desired.txt'
    dataAnalysis_xyz_ref_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_xyz_ref.txt'
    dataAnalysis_accuracy_thr_path: '/home/dijkd/franka_ws/src/franka_ros/new_controllers/outputData/V4_env_1_fix_accuracy_thr.txt'